/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import bd.DAO_Usuarios;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.List;
import javax.swing.JOptionPane;
import model.Usuario;

/**
 *
 * @author lvved
 */
public class GestionTrabajadores extends javax.swing.JFrame {

    /**
     * Creates new form GestionTrabajadores
     */
    public GestionTrabajadores() {
        initComponents();
        cargarComboIds();
    }
    
    
    private void cargarComboIds() {
    try {
        DAO_Usuarios dao = new DAO_Usuarios();
        List<Integer> ids = dao.obtenerIdsUsuarios();
        cbbidTrabajador.removeAllItems();
        for (int id : ids) {
            cbbidTrabajador.addItem(String.valueOf(id));
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al cargar IDs: " + ex.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitulo = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAgregarTrabajador = new javax.swing.JTable();
        lblNombreTrabajador = new javax.swing.JLabel();
        lblCorreoTrabajador = new javax.swing.JLabel();
        lblContraseñaTrabajador = new javax.swing.JLabel();
        lblRolTrabajador = new javax.swing.JLabel();
        txtContraseñaTrabajador = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtNombreTrabajador = new javax.swing.JTextField();
        txtCorreoTrabajador = new javax.swing.JTextField();
        cbbRolTrabajador = new javax.swing.JComboBox<>();
        lblFechaCreacion = new javax.swing.JLabel();
        txtFechaCreacion = new javax.swing.JTextField();
        btnCancelarRegistro = new javax.swing.JButton();
        btnAgregarRegistro = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblModProveedor = new javax.swing.JTable();
        lblModificarNombreTrabajador = new javax.swing.JLabel();
        txtModificarNombreTrabajador = new javax.swing.JTextField();
        lblModificarCorreoTrabajador = new javax.swing.JLabel();
        txtModificarCorreoTrabajador = new javax.swing.JTextField();
        lblModificarContrasenaTrabajador = new javax.swing.JLabel();
        txtModificarContrasenaTrabajador = new javax.swing.JTextField();
        cbbModificarRol = new javax.swing.JComboBox<>();
        lblModificarRol = new javax.swing.JLabel();
        lblModificarFechaCreacion = new javax.swing.JLabel();
        txtModificarFechaCreacion = new javax.swing.JTextField();
        btnCancelarUpdate = new javax.swing.JButton();
        btnAgregarUpdate = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        lblidTrabajador = new javax.swing.JLabel();
        cbbidTrabajador = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblEliminarProveedor = new javax.swing.JTable();
        lblEliminarProveedor = new javax.swing.JLabel();
        btnEliminarProveedor = new javax.swing.JButton();
        cbbBorrarIdProveedor = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblProducto_Proveedor = new javax.swing.JTable();
        lblAsociarProveedor = new javax.swing.JLabel();
        cbbAsociarProveedor = new javax.swing.JComboBox<>();
        btnAsociar = new javax.swing.JButton();
        lblAsociarProducto = new javax.swing.JLabel();
        cbbAsociarProducto = new javax.swing.JComboBox<>();
        btnQuitarAsociacion = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        lblLogoTH = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlTitulo.setBackground(new java.awt.Color(0, 0, 0));

        jTabbedPane1.setBackground(new java.awt.Color(102, 0, 102));
        jTabbedPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 2, true));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(28, 28, 28));

        tblAgregarTrabajador.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        tblAgregarTrabajador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAgregarTrabajador.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblAgregarTrabajador.setSelectionBackground(new java.awt.Color(178, 223, 219));
        jScrollPane1.setViewportView(tblAgregarTrabajador);

        lblNombreTrabajador.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblNombreTrabajador.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreTrabajador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreTrabajador.setText("Nombre/Apellido Trabajador");

        lblCorreoTrabajador.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblCorreoTrabajador.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreoTrabajador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCorreoTrabajador.setText("Direccion de Correo");

        lblContraseñaTrabajador.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblContraseñaTrabajador.setForeground(new java.awt.Color(255, 255, 255));
        lblContraseñaTrabajador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblContraseñaTrabajador.setText("Contraseña");

        lblRolTrabajador.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblRolTrabajador.setForeground(new java.awt.Color(255, 255, 255));
        lblRolTrabajador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRolTrabajador.setText("Rol");

        txtContraseñaTrabajador.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        txtContraseñaTrabajador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtContraseñaTrabajadorMouseClicked(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtNombreTrabajador.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        txtNombreTrabajador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreTrabajadorKeyTyped(evt);
            }
        });

        txtCorreoTrabajador.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        txtCorreoTrabajador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoTrabajadorKeyTyped(evt);
            }
        });

        cbbRolTrabajador.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        cbbRolTrabajador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empleado\t", "Administrador" }));

        lblFechaCreacion.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblFechaCreacion.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaCreacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFechaCreacion.setText("Fecha de Creación");

        txtFechaCreacion.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        txtFechaCreacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFechaCreacionMouseClicked(evt);
            }
        });

        btnCancelarRegistro.setBackground(new java.awt.Color(204, 0, 51));
        btnCancelarRegistro.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        btnCancelarRegistro.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarRegistro.setText("CANCELAR");
        btnCancelarRegistro.setBorder(null);
        btnCancelarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarRegistroActionPerformed(evt);
            }
        });

        btnAgregarRegistro.setBackground(new java.awt.Color(0, 153, 51));
        btnAgregarRegistro.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        btnAgregarRegistro.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarRegistro.setText("AGREGAR");
        btnAgregarRegistro.setBorder(null);
        btnAgregarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreTrabajador)
                            .addComponent(txtContraseñaTrabajador)
                            .addComponent(lblNombreTrabajador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblContraseñaTrabajador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelarRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCorreoTrabajador)
                            .addComponent(txtCorreoTrabajador)
                            .addComponent(lblRolTrabajador)
                            .addComponent(cbbRolTrabajador, 0, 263, Short.MAX_VALUE)
                            .addComponent(btnAgregarRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblFechaCreacion)
                    .addComponent(txtFechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCorreoTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorreoTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lblContraseñaTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(lblRolTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtContraseñaTrabajador, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(cbbRolTrabajador))
                        .addGap(28, 28, 28)
                        .addComponent(lblFechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(txtFechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Agregar Trabajador", jPanel2);

        jPanel7.setBackground(new java.awt.Color(28, 28, 28));

        tblModProveedor.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        tblModProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblModProveedor.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblModProveedor.setSelectionBackground(new java.awt.Color(178, 223, 219));
        jScrollPane2.setViewportView(tblModProveedor);

        lblModificarNombreTrabajador.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblModificarNombreTrabajador.setForeground(new java.awt.Color(255, 255, 255));
        lblModificarNombreTrabajador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModificarNombreTrabajador.setText("Nombre/Apellido Trabajador");

        txtModificarNombreTrabajador.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        txtModificarNombreTrabajador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtModificarNombreTrabajadorKeyTyped(evt);
            }
        });

        lblModificarCorreoTrabajador.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblModificarCorreoTrabajador.setForeground(new java.awt.Color(255, 255, 255));
        lblModificarCorreoTrabajador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModificarCorreoTrabajador.setText("Direccion de Correo");

        txtModificarCorreoTrabajador.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        txtModificarCorreoTrabajador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtModificarCorreoTrabajadorKeyTyped(evt);
            }
        });

        lblModificarContrasenaTrabajador.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblModificarContrasenaTrabajador.setForeground(new java.awt.Color(255, 255, 255));
        lblModificarContrasenaTrabajador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblModificarContrasenaTrabajador.setText("Contraseña");

        txtModificarContrasenaTrabajador.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        txtModificarContrasenaTrabajador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtModificarContrasenaTrabajadorMouseClicked(evt);
            }
        });

        cbbModificarRol.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        cbbModificarRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empleado", "Administrador" }));

        lblModificarRol.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblModificarRol.setForeground(new java.awt.Color(255, 255, 255));
        lblModificarRol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModificarRol.setText("Rol");

        lblModificarFechaCreacion.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblModificarFechaCreacion.setForeground(new java.awt.Color(255, 255, 255));
        lblModificarFechaCreacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblModificarFechaCreacion.setText("Fecha de Creación");

        txtModificarFechaCreacion.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        txtModificarFechaCreacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtModificarFechaCreacionMouseClicked(evt);
            }
        });

        btnCancelarUpdate.setBackground(new java.awt.Color(204, 0, 51));
        btnCancelarUpdate.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        btnCancelarUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarUpdate.setText("CANCELAR");
        btnCancelarUpdate.setBorder(null);
        btnCancelarUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarUpdateActionPerformed(evt);
            }
        });

        btnAgregarUpdate.setBackground(new java.awt.Color(0, 153, 51));
        btnAgregarUpdate.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        btnAgregarUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarUpdate.setText("AGREGAR");
        btnAgregarUpdate.setBorder(null);
        btnAgregarUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarUpdateActionPerformed(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblidTrabajador.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblidTrabajador.setForeground(new java.awt.Color(255, 255, 255));
        lblidTrabajador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblidTrabajador.setText("ID Trabajador");
        lblidTrabajador.setToolTipText("");
        lblidTrabajador.setFocusable(false);

        cbbidTrabajador.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCancelarUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(lblModificarFechaCreacion)
                            .addComponent(txtModificarFechaCreacion, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(txtModificarContrasenaTrabajador)
                            .addComponent(lblModificarContrasenaTrabajador, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(lblidTrabajador)
                            .addComponent(cbbidTrabajador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblModificarCorreoTrabajador)
                                .addComponent(lblModificarRol)
                                .addComponent(txtModificarCorreoTrabajador)
                                .addComponent(cbbModificarRol, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAgregarUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtModificarNombreTrabajador)
                                .addComponent(lblModificarNombreTrabajador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(lblModificarNombreTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtModificarNombreTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbbidTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblidTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(lblModificarContrasenaTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(txtModificarContrasenaTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(lblModificarFechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(txtModificarFechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(lblModificarCorreoTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtModificarCorreoTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(lblModificarRol, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(cbbModificarRol, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregarUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelarUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1401, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Modificar Trabajador", jPanel3);

        jPanel6.setBackground(new java.awt.Color(28, 28, 28));

        tblEliminarProveedor.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        tblEliminarProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEliminarProveedor.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblEliminarProveedor.setSelectionBackground(new java.awt.Color(178, 223, 219));
        jScrollPane4.setViewportView(tblEliminarProveedor);

        lblEliminarProveedor.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        lblEliminarProveedor.setForeground(new java.awt.Color(255, 255, 255));
        lblEliminarProveedor.setText("ID Proveedor a Eliminar");

        btnEliminarProveedor.setBackground(new java.awt.Color(123, 51, 54));
        btnEliminarProveedor.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        btnEliminarProveedor.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarProveedor.setText("Eliminar Proveedor");
        btnEliminarProveedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProveedorActionPerformed(evt);
            }
        });

        cbbBorrarIdProveedor.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        cbbBorrarIdProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbBorrarIdProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbBorrarIdProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEliminarProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnEliminarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbbBorrarIdProveedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(lblEliminarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbbBorrarIdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1341, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Eliminar Trabajador", jPanel5);

        jPanel1.setBackground(new java.awt.Color(28, 28, 28));

        tblProducto_Proveedor.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        tblProducto_Proveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProducto_Proveedor.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblProducto_Proveedor.setSelectionBackground(new java.awt.Color(178, 223, 219));
        jScrollPane5.setViewportView(tblProducto_Proveedor);

        lblAsociarProveedor.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblAsociarProveedor.setForeground(new java.awt.Color(255, 255, 255));
        lblAsociarProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAsociarProveedor.setText("ID Proveedor ");

        cbbAsociarProveedor.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        cbbAsociarProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbAsociarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbAsociarProveedorActionPerformed(evt);
            }
        });

        btnAsociar.setBackground(new java.awt.Color(76, 158, 76));
        btnAsociar.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        btnAsociar.setForeground(new java.awt.Color(255, 255, 255));
        btnAsociar.setText("Agregar Asociación");
        btnAsociar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAsociar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsociarActionPerformed(evt);
            }
        });

        lblAsociarProducto.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblAsociarProducto.setForeground(new java.awt.Color(255, 255, 255));
        lblAsociarProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAsociarProducto.setText("ID Producto\n");

        cbbAsociarProducto.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        cbbAsociarProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbAsociarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbAsociarProductoActionPerformed(evt);
            }
        });

        btnQuitarAsociacion.setBackground(new java.awt.Color(123, 51, 54));
        btnQuitarAsociacion.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        btnQuitarAsociacion.setForeground(new java.awt.Color(255, 255, 255));
        btnQuitarAsociacion.setText("Eliminar Asociación");
        btnQuitarAsociacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnQuitarAsociacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarAsociacionActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbbAsociarProducto, 0, 170, Short.MAX_VALUE)
                            .addComponent(lblAsociarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbbAsociarProveedor, 0, 170, Short.MAX_VALUE)
                            .addComponent(lblAsociarProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(55, 55, 55))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAsociar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQuitarAsociacion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148)))
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblAsociarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbbAsociarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblAsociarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbbAsociarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(84, 84, 84)
                        .addComponent(btnAsociar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnQuitarAsociacion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", jPanel1);

        jPanel4.setBackground(new java.awt.Color(51, 0, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/emblem-of-hirata-gifu-seeklogo (1).png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/hirata-seeklogo (3).png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogoTH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTituloLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(lblLogoTH))
                    .addGroup(pnlTituloLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(587, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtContraseñaTrabajadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraseñaTrabajadorMouseClicked

    }//GEN-LAST:event_txtContraseñaTrabajadorMouseClicked

    private void txtNombreTrabajadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreTrabajadorKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isLetter(c) && c != ' ' && c != '\b') { // Permite letras, espacio y tecla borrar
            evt.consume(); // Bloquea la entrada del carácter
        }
    }//GEN-LAST:event_txtNombreTrabajadorKeyTyped

    private void btnEliminarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProveedorActionPerformed
        
    }//GEN-LAST:event_btnEliminarProveedorActionPerformed

    private void cbbBorrarIdProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbBorrarIdProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbBorrarIdProveedorActionPerformed

    private void cbbAsociarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbAsociarProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbAsociarProveedorActionPerformed

    private void btnAsociarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsociarActionPerformed
        
    }//GEN-LAST:event_btnAsociarActionPerformed

    private void cbbAsociarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbAsociarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbAsociarProductoActionPerformed

    private void btnQuitarAsociacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarAsociacionActionPerformed
        
    }//GEN-LAST:event_btnQuitarAsociacionActionPerformed

    private void txtCorreoTrabajadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoTrabajadorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoTrabajadorKeyTyped

    private void txtFechaCreacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaCreacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaCreacionMouseClicked

    private void btnCancelarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarRegistroActionPerformed
        txtNombreTrabajador.setText("");
        txtCorreoTrabajador.setText("");
        txtContraseñaTrabajador.setText("");
        cbbRolTrabajador.setSelectedIndex(0); // Selecciona la primera opción del combo
        txtFechaCreacion.setText(""); // O si usas JDateChooser: dateChooser.setDate(null);
    }//GEN-LAST:event_btnCancelarRegistroActionPerformed

    private void btnAgregarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRegistroActionPerformed
        try {
            Usuario nuevoUsuario = new Usuario();
            nuevoUsuario.setNombreCompleto(txtNombreTrabajador.getText());
            nuevoUsuario.setCorreo(txtCorreoTrabajador.getText());
            nuevoUsuario.setContrasena(txtContraseñaTrabajador.getText());
            nuevoUsuario.setRol(cbbRolTrabajador.getSelectedItem().toString());

            // Si usas JTextField para fecha
            java.util.Date fecha = java.sql.Date.valueOf(txtFechaCreacion.getText()); // formato: yyyy-MM-dd
            nuevoUsuario.setFechaCreacion(fecha);

            DAO_Usuarios dao = new DAO_Usuarios();
            dao.agregarUsuario(nuevoUsuario);

            JOptionPane.showMessageDialog(this, "Usuario agregado correctamente.");
            btnCancelarRegistroActionPerformed(null); // Limpia los campos
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al agregar usuario: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnAgregarRegistroActionPerformed

    private void txtModificarNombreTrabajadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModificarNombreTrabajadorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModificarNombreTrabajadorKeyTyped

    private void txtModificarCorreoTrabajadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModificarCorreoTrabajadorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModificarCorreoTrabajadorKeyTyped

    private void txtModificarContrasenaTrabajadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtModificarContrasenaTrabajadorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModificarContrasenaTrabajadorMouseClicked

    private void txtModificarFechaCreacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtModificarFechaCreacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModificarFechaCreacionMouseClicked

    private void btnCancelarUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarUpdateActionPerformed
        txtModificarNombreTrabajador.setText("");
        txtModificarCorreoTrabajador.setText("");
        txtModificarContrasenaTrabajador.setText("");
        cbbModificarRol.setSelectedIndex(0);
        txtFechaCreacion.setText("");
        cbbidTrabajador.setSelectedIndex(0);
        cargarComboIds();
    }//GEN-LAST:event_btnCancelarUpdateActionPerformed

    private void btnAgregarUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUpdateActionPerformed
        try {
            int idSeleccionado = Integer.parseInt(cbbidTrabajador.getSelectedItem().toString());
            Usuario usuario = new Usuario();
            usuario.setIdUsuario(idSeleccionado);
            usuario.setNombreCompleto(txtModificarNombreTrabajador.getText());
            usuario.setCorreo(txtModificarCorreoTrabajador.getText());
            usuario.setContrasena(txtModificarContrasenaTrabajador.getText());
            usuario.setRol(cbbModificarRol.getSelectedItem().toString());

            // Fecha
            java.util.Date fecha = java.sql.Date.valueOf(txtModificarFechaCreacion.getText()); // formato yyyy-MM-dd
            usuario.setFechaCreacion(fecha);

            DAO_Usuarios dao = new DAO_Usuarios();
            dao.modificarUsuario(usuario);
            cargarComboIds();

            JOptionPane.showMessageDialog(this, "Usuario modificado correctamente.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al modificar usuario: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnAgregarUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatLaf look and feel */
        try {
            // Configura FlatLaf (estilo claro)
            FlatLightLaf.setup();

            // También puedes usar FlatDarkLaf para un tema oscuro
            // com.formdev.flatlaf.FlatDarkLaf.setup();
        } catch (Exception ex) {
            System.err.println("Failed to initialize FlatLaf");
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionTrabajadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarRegistro;
    private javax.swing.JButton btnAgregarUpdate;
    private javax.swing.JButton btnAsociar;
    private javax.swing.JButton btnCancelarRegistro;
    private javax.swing.JButton btnCancelarUpdate;
    private javax.swing.JButton btnEliminarProveedor;
    private javax.swing.JButton btnQuitarAsociacion;
    private javax.swing.JComboBox<String> cbbAsociarProducto;
    private javax.swing.JComboBox<String> cbbAsociarProveedor;
    private javax.swing.JComboBox<String> cbbBorrarIdProveedor;
    private javax.swing.JComboBox<String> cbbModificarRol;
    private javax.swing.JComboBox<String> cbbRolTrabajador;
    private javax.swing.JComboBox<String> cbbidTrabajador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAsociarProducto;
    private javax.swing.JLabel lblAsociarProveedor;
    private javax.swing.JLabel lblContraseñaTrabajador;
    private javax.swing.JLabel lblCorreoTrabajador;
    private javax.swing.JLabel lblEliminarProveedor;
    private javax.swing.JLabel lblFechaCreacion;
    private javax.swing.JLabel lblLogoTH;
    private javax.swing.JLabel lblModificarContrasenaTrabajador;
    private javax.swing.JLabel lblModificarCorreoTrabajador;
    private javax.swing.JLabel lblModificarFechaCreacion;
    private javax.swing.JLabel lblModificarNombreTrabajador;
    private javax.swing.JLabel lblModificarRol;
    private javax.swing.JLabel lblNombreTrabajador;
    private javax.swing.JLabel lblRolTrabajador;
    private javax.swing.JLabel lblidTrabajador;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTable tblAgregarTrabajador;
    private javax.swing.JTable tblEliminarProveedor;
    private javax.swing.JTable tblModProveedor;
    private javax.swing.JTable tblProducto_Proveedor;
    private javax.swing.JTextField txtContraseñaTrabajador;
    private javax.swing.JTextField txtCorreoTrabajador;
    private javax.swing.JTextField txtFechaCreacion;
    private javax.swing.JTextField txtModificarContrasenaTrabajador;
    private javax.swing.JTextField txtModificarCorreoTrabajador;
    private javax.swing.JTextField txtModificarFechaCreacion;
    private javax.swing.JTextField txtModificarNombreTrabajador;
    private javax.swing.JTextField txtNombreTrabajador;
    // End of variables declaration//GEN-END:variables
}
